name: AutoDeploy # 设置工作流的名称

on:
  push: # 设置触发事件为 push 事件
    branches:
      - main # 仅当推送到 main 分支时触发
    paths-ignore: # 忽略的文件或目录
      - LICENSE
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
      - name: Checkout
          uses: actions/checkout@v3
      - name: Setup
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'npm'
      - name: Install
          run: npm install
      - name: Build
          if: ${{ steps.release.outputs.release_created }}
          run: npm run build
       # 部署到 GitHub Pages
       - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.3.3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
            BRANCH: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
            FOLDER: dist
